### ISSUE TITLE
[feature/development request] Online Clipboard

### ISSUE THREAD

**Issue by Linecutterx** [tobychui/WebStick#1]
This would be a perfect way to implement an internet clipboard (text/URL/small file/image) to share things between (your own) devices.

Probably best to use pre-shared keys (a la wireguard) to secure the private content.
Also a configured auto-delete interval (or some 
kind of option to set a longer lifespan) to keep the used storage space under control.
A mini pastebin for wider sharing could also be useful (supporting bigger texts, with a shareable URL).

Which kind of means an API & probably a forked project from the AIO solution that you've created.

**Comment by tobychui** [comment]
Thanks for the idea. 
I am not using pastebin and I personally use ArozOS for most of my tmp file storage (with auto cleaning every 24 hours). I don't feel like implementing another solution is needed in my use cases. 
As always, PR are welcomed :)
