### ISSUE TITLE
Multi User problem

### ISSUE THREAD

**Issue by dobrishinov** [tobychui/WebStick#2]
Hey, that project is awesome!

I'm using NodeMcu or Wemos D1, both with an SD card extension. Everything works fine, but I encountered some issues when adding a new user. For example, I created a new user with the username "Test" and password "12345678," but I'm unable to log in with this user. The web auth value in the cookies changes, but attempting to log in with the new user redirects to the admin page briefly before redirecting back to the login page. Logging in as an admin works initially, but after several attempts with the new user, the admin pages fail to load correctly. Some responses are incomplete, and I see strange code fragments on some pages, suggesting the ESP8266 struggles with parsing the page.

I've investigated and believe I've identified the problem, though I'm unsure how to fix it yet. By default, the directories SD/db/auth/ and SD/db/sess/ are empty, which is fine.

When logging in as admin, a cookie file is created in SD/db/auth/ with the correct value:

- In Browser: web-auth | 42222fb1d35139
- In SD/db/auth/cookie: 42222fb1d35139
- In SD/db/sess/, there's nothing. I think we need the cookie value here as well.

When attempting to log in with the new user, we get redirected to the admin page momentarily before returning to the login page, even though the browser has a cookie. A session file is created in SD/db/sess/ but nothing in SD/db/auth/.

- In Browser: web-auth | dfa3ef16492f46
- In SD/db/auth/: No cookie
- In SD/db/sess/: File dfa3ef16492f46 containing the username

Manually creating a cookie file in SD/db/auth/ with this value (dfa3ef16492f46) allows me to log in as the new user.

Logging out deletes the cookie from the browser, but the session files remain in SD/db/auth/cookie and SD/db/sess/. On attempting to log in again, a new cookie value is created in the browser, and a new session file is created in SD/db/sess/, but the old session still allows login due to its lingering cookie value.

If I try to log in as admin at this point, the cookie in SD/db/auth/cookie updates with the new value, but SD/db/sess/ still contains the old session from the custom user. I hope this explanation clarifies the problem.

**Comment by tobychui** [comment]
It feels like a hardware problem, maybe the SPI connections between the SD card and your ESP8266. You sure you have all wires soldered on and well connected?

**Comment by dobrishinov** [comment]
> It feels like a hardware problem, maybe the SPI connections between the SD card and your ESP8266. You sure you have all wires soldered on and well connected?

I don't think so, because last night I tested with the admin user and everything is working perfectly fine. Today I tried to create a new user but the new user is not able to log in, when I tried many times I saw that the file in sess are created but not in the auth for the new user, When I deleted it manually from the SD card the sess files, with admin user I don't have a problem until I try with the newly created user. Something with the session and the cookies is not right but I don't know what... Do you have some bin file for the firmware just to try?

**Comment by tobychui** [comment]
@dobrishinov 
Here you go
[web-server.ino.d1_mini.zip](https://github.com/tobychui/WebStick/files/15500579/web-server.ino.d1_mini.zip)

**Comment by dobrishinov** [comment]
> @dobrishinov Here you go [web-server.ino.d1_mini.zip](https://github.com/tobychui/WebStick/files/15500579/web-server.ino.d1_mini.zip)

Hey, thanks for the bin. I successfully flash the ESP but again I have the same problem with the user different from Admin. Everything is working perfectly, Able to upload, download files, have access, etc, But is not possible to login as created user. If you want I can record a video session, because from what I saw something is happen in the authorization and the session file or cookie file in the sd card...

**Comment by tobychui** [comment]
@dobrishinov Well it works on my WebStick v3 (opening admin & test user on two browsers, left Firefox, right Edge)
![圖片](https://github.com/tobychui/WebStick/assets/24617523/04749e26-7033-491a-90c4-52dd325e0aa3)

Maybe you have a defective ESP8266 or something? Have you tried another ESP8266 module?

**Comment by dobrishinov** [comment]
> @dobrishinov Well it works on my WebStick v3 (opening admin & test user on two browsers, left Firefox, right Edge) ![圖片](https://private-user-images.githubusercontent.com/24617523/335212538-04749e26-7033-491a-90c4-52dd325e0aa3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNzg0NDgsIm5iZiI6MTcxNzA3ODE0OCwicGF0aCI6Ii8yNDYxNzUyMy8zMzUyMTI1MzgtMDQ3NDllMjYtNzAzMy00OTFhLTkwYzQtNTJkZDMyNWUwYWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDE0MDkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4NTgwODhkNjZmNWM3MjYyMDIzNzRiNGZiNTZkMzRhYjBmNzkyMTMwM2ZhYWU3MzY5ZGE4ZTEzMTk1ZTFkNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zU2wPX5RR7Nou1qKnFrvI0GAHgZhXzMvc4Ev4lb1YfU)
> 
> Maybe you have a defective ESP8266 or something? Have you tried another ESP8266 module?

Lol... I tried also from Chrome and Edge and it's working! So I suspected something strange between my Chrome sessions was happening. I don't know why. When I tried from different browsers everything worked perfectly!

I have one question about the different users, what is their purpose? I saw the differences between Admin and other users are that Admin has rights to create/delete users only. There is no separation of level restriction between users, right? Just wonder if is it possible to access the audio player without a logged user or to make only a specific user to have access to the audio player.

Thanks a lot!

**Comment by tobychui** [comment]
@dobrishinov 

Yes, user is admin except they cant create or edit other user's credentials. 

The WebStick OS is a trim down version of the [ArozOS](https://arozos.com/). You will find the full version of the File Manager and Audio player inside the ArozOS equip with full user permission systems.

If you need such feature, you should get an old Raspberry Pi 2 / 3 or something similar for slightly more money and install ArozOS.

**Comment by dobrishinov** [comment]
> @dobrishinov
> 
> Yes, user is admin except they cant create or edit other user's credentials.
> 
> The WebStick OS is a trim down version of the [ArozOS](https://arozos.com/). You will find the full version of the File Manager and Audio player inside the ArozOS equip with full user permission systems.
> 
> If you need such feature, you should get an old Raspberry Pi 2 / 3 or something similar for slightly more money and install ArozOS.

Good to know. Thanks for the info! I'll check. But it's fun to play on esp8266 because I think this firmware is working very well from what I tested. I enhanced a little bit the audio player, added a search for the list, added shuffle, and small UI improvements, maybe when I add the things that I have in my mind will create a pull request. 
I thinking also of creating some user permissions levels, but let's see. I didn't see how many memory is left up to now on the ESP. Do you remember?

**Comment by tobychui** [comment]
@dobrishinov I think it is pretty much full. If you need more complex data structure, I guess you will need to move some data into the SD card and use it as the `/tmp` folder in Linux. Anyway, looking forward to your PR :)

**Comment by dobrishinov** [comment]
Good suggestion about the /tmp. I'll think about it.
Thanks again!

**Comment by dobrishinov** [comment]
Good suggestion about the /tmp. I'll think about it.
Thanks again!
